In [1]:
import os
import json

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from datasets import load_dataset

/usr/workspace/wsb/kirchenb/tuolumne_conda_28_630_fiction/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
BASE_OUTPUT_PATH = "/p/vast1/kirchenb/fiction_stash/lit-gpt-dev-fiction/output"

# "/p/vast1/kirchenb/fiction_stash/lit-gpt-dev-fiction/output/v6_exp1_train_val_splits_5pct_seed1234/exp1_train_val_splits_5pct_4N_mb8-wb128_llama-3-1-8B_event-split-fictions-train-val/lm_eval_results/hf_checkpoint_step-00000499-exp1_train_val_splits_5pct_4N_mb8-wb128_llama-3-1-8B_event-split-fictions-train-val/samples_fict_qa_obqa_blind_inf_ex_dedup_ds_mcq_2025-04-07T11-10-31.722834.jsonl"

# full performance breakdown is in
# "/p/vast1/kirchenb/fiction_stash/lit-gpt-dev-fiction/output/v6_exp1_train_val_splits_5pct_seed1234/exp1_train_val_splits_5pct_4N_mb8-wb128_llama-3-1-8B_event-split-fictions-train-val/lm_eval_results/hf_checkpoint_step-00000499-exp1_train_val_splits_5pct_4N_mb8-wb128_llama-3-1-8B_event-split-fictions-train-val/results_2025-04-13T13-47-48.383939.json"

RUN_GRP = "v6_exp1_train_val_splits_5pct_seed1234"
RUN_NAME = "exp1_train_val_splits_5pct_4N_mb8-wb128_llama-3-1-8B_event-split-fictions-train-val"
RESULT_SUBDIR = "lm_eval_results"
INIT_CKPT_STEP = "hf_checkpoint_step-00000000"
FINAL_CKPT_STEP = "hf_checkpoint_step-00000499"
INIT_FILENAME = "samples_fict_qa_obqa_blind_inf_ex_dedup_ds_mcq_2025-04-07T10-34-04.100979.jsonl"
FINAL_FILENAME = "samples_fict_qa_obqa_blind_inf_ex_dedup_ds_mcq_2025-04-07T11-10-31.722834.jsonl"

INIT_FULL_JSONL_PATH = f"{BASE_OUTPUT_PATH}/{RUN_GRP}/{RUN_NAME}/{RESULT_SUBDIR}/{INIT_CKPT_STEP}-{RUN_NAME}/{INIT_FILENAME}"
FINAL_FULL_JSONL_PATH = f"{BASE_OUTPUT_PATH}/{RUN_GRP}/{RUN_NAME}/{RESULT_SUBDIR}/{FINAL_CKPT_STEP}-{RUN_NAME}/{FINAL_FILENAME}"

In [3]:
def load_jsonl_to_dataframe(file_path: str) -> pd.DataFrame:
    """
    Loads data from a JSON Lines (.jsonl) file into a flattened pandas DataFrame.

    This function reads the file line by line, parses each line as a JSON object,
    and uses pd.json_normalize to automatically flatten nested dictionaries, 
    creating clear column names (e.g., 'doc_event_id', 'doc_natural_answer').

    Args:
        file_path: The full path to the .jsonl file.

    Returns:
        A pandas DataFrame containing the flattened tabular data.
    """
    try:
        # 1. Read the JSONL file line by line and parse it into a list of dictionaries
        with open(file_path, 'r', encoding='utf-8') as f:
            data = [json.loads(line) for line in f]

        # 2. Use pd.json_normalize to flatten the data
        # 'sep' defines the separator for nested keys (e.g., 'doc' + '_' + 'event_id')
        df = pd.json_normalize(
            data,
            sep='_',
            errors='ignore' # Use 'ignore' to skip lines or fields that don't conform
        )
        
        print(f"Successfully loaded and flattened {len(df)} records.")
        return df

    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return pd.DataFrame()
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        return pd.DataFrame()
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return pd.DataFrame()

def extract_choice_from_jsonl_df(df):
    """ Model attempt is specified by a series of scores for each choice under the "resps" key.
    
    "resps": [[["-19.20279312133789", "False"]], [["-27.694900512695312", "False"]], [["-26.183048248291016", "False"]], [["-31.78978729248047", "False"]]]
    """
    choice_indices = []
    ranking_lists = []
    for idx, row in df.iterrows():
        resps = row['resps']
        # extract the scores for each choice
        scores = [float(choice[0][0]) for choice in resps]
        # find the index of the choice with the highest score (least negative)
        best_choice_index = int(np.argmax(scores))
        ranking = np.argsort(scores)[::-1]  # descending order
        choice_indices.append(best_choice_index)
        ranking_lists.append(ranking.tolist())
    df['model_choice'] = choice_indices
    df['choice_ranking'] = ranking_lists

    return df

def basic_performance_analysis(df: pd.DataFrame, verdict_col_name: str = "acc") -> None:
    """
    Performs basic performance analysis on the MCQ results DataFrame.

    This function calculates and prints the overall accuracy, 
    as well as accuracy per question type if available.

    Args:
        df: The pandas DataFrame containing the MCQ results.
    """
    if df.empty:
        print("DataFrame is empty. Cannot perform analysis.")
        return

    # Calculate overall accuracy
    total_questions = len(df)
    verdict_col_data = df[verdict_col_name].astype(bool)
    correct_answers = df[verdict_col_name].sum()
    overall_accuracy = correct_answers / total_questions if total_questions > 0 else 0

    print(f"Overall Accuracy: {overall_accuracy:.2%} ({correct_answers}/{total_questions})")

    # If 'question_type' column exists, calculate accuracy per question type
    if 'question_type' in df.columns:
        accuracy_by_type = df.groupby('question_type')['is_correct'].mean()
        print("\nAccuracy by Question Type:")
        for q_type, acc in accuracy_by_type.items():
            print(f"  {q_type}: {acc:.2%}")

def pull_raw_dataset(hf_repo_id: str, config_name: str, split:str="train"):
    dataset = load_dataset(hf_repo_id, config_name, split=split)
    # convert to dataframe
    df = dataset.to_pandas()
    return df

In [4]:
df_lm_eval_init_result = load_jsonl_to_dataframe(INIT_FULL_JSONL_PATH)
df_lm_eval_final_result = load_jsonl_to_dataframe(FINAL_FULL_JSONL_PATH)
# df_lm_eval_final_result

df_lm_eval_init_result = extract_choice_from_jsonl_df(df_lm_eval_init_result)
df_lm_eval_final_result = extract_choice_from_jsonl_df(df_lm_eval_final_result)


df_lm_eval_final_result["acc_init"] = df_lm_eval_init_result["acc"]
df_lm_eval_final_result["acc_final"] = df_lm_eval_final_result["acc"]
df_lm_eval_final_result["model_choice_init"] = df_lm_eval_init_result["model_choice"]
df_lm_eval_final_result["model_choice_final"] = df_lm_eval_final_result["model_choice"]
df_lm_eval_final_result["choice_ranking_init"] = df_lm_eval_init_result["choice_ranking"]
df_lm_eval_final_result["choice_ranking_final"] = df_lm_eval_final_result["choice_ranking"]

df_lm_eval_final_result['target'] = df_lm_eval_final_result['target'].astype(int)

# there seems to be a spurious answer "Western and Eastern"
# make a col indicating when it is in the choice list
df_lm_eval_final_result['W_and_E_in_choices'] = df_lm_eval_final_result['doc_topk_choices'].apply(lambda choices: "Western and Eastern" in choices)
df_lm_eval_final_result['W_and_E_is_model_choice_init'] = df_lm_eval_final_result[['model_choice_init', 'doc_topk_choices']].apply(
    lambda row: row['doc_topk_choices'][row['model_choice_init']] == "Western and Eastern", axis=1
) 
df_lm_eval_final_result['W_and_E_is_model_choice_final'] = df_lm_eval_final_result[['model_choice_final', 'doc_topk_choices']].apply(
    lambda row: row['doc_topk_choices'][row['model_choice_final']] == "Western and Eastern", axis=1
)

df_lm_eval_final_result

Successfully loaded and flattened 3036 records.
Successfully loaded and flattened 3036 records.

,doc_id,target,resps,filtered_resps,filter,metrics,doc_hash,prompt_hash,target_hash,acc,...,choice_ranking,acc_init,acc_final,model_choice_init,model_choice_final,choice_ranking_init,choice_ranking_final,W_and_E_in_choices,W_and_E_is_model_choice_init,W_and_E_is_model_choice_final
0,0,2,"[[[-46.50212860107422, False]], [[-38.50323104...","[[-46.50212860107422, False], [-38.50323104858...",none,"[acc, acc_norm]",c729dfa8379ae2dbcb1c7f65117aac63bbd716e3131164...,f3cff83b03a08fc897cb5b798abf6f616e202574fce38e...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1.0,...,"[2, 3, 1, 0]",1.0,1.0,2,2,"[2, 3, 1, 0]","[2, 3, 1, 0]",False,False,False
1,1,0,"[[[-24.992748260498047, False]], [[-24.4700202...","[[-24.992748260498047, False], [-24.4700202941...",none,"[acc, acc_norm]",4d44cd3433eb55ce4b9bd76fb12dca098a8cc2ae21bf2a...,e45a87c16ce89047fc3377f0d7f8dd136e06f68a24e57b...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,0.0,...,"[3, 1, 0, 2]",0.0,0.0,3,3,"[3, 1, 0, 2]","[3, 1, 0, 2]",False,False,False
2,2,2,"[[[-17.62920379638672, False]], [[-27.24129104...","[[-17.62920379638672, False], [-27.24129104614...",none,"[acc, acc_norm]",31f9277df4adea7a08fc8914c8f01d181c438c7c6b69f7...,16a6d8f1c33f66cdfb3b85d888205d6eb98410e852eaea...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0.0,...,"[0, 2, 3, 1]",0.0,0.0,0,0,"[0, 2, 1, 3]","[0, 2, 3, 1]",False,False,False
3,3,2,"[[[-33.734130859375, False]], [[-20.2086391448...","[[-33.734130859375, False], [-20.2086391448974...",none,"[acc, acc_norm]",a5321b7d032d95270a23d34a6d0c92da64c1d6996c74c2...,5439e357c8edeb897df57f00b4f43a6bc9879d8a4fd496...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1.0,...,"[2, 1, 0, 3]",0.0,1.0,1,2,"[1, 0, 2, 3]","[2, 1, 0, 3]",True,False,False
4,4,3,"[[[-24.063854217529297, False]], [[-29.4297676...","[[-24.063854217529297, False], [-29.4297676086...",none,"[acc, acc_norm]",8959cd27ebc59ce3f66e3f0e896386066563fc89da2793...,6d4ee26ac87d2f203ffcb8f0497d12c9afac909a973a8e...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,0.0,...,"[2, 3, 0, 1]",0.0,0.0,2,2,"[2, 3, 0, 1]","[2, 3, 0, 1]",False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3031,3031,3,"[[[-31.122352600097656, False]], [[-17.3408241...","[[-31.122352600097656, False], [-17.3408241271...",none,"[acc, acc_norm]",0ce58ce2a73fa6ec512a9dec64f3c9dc58c6d4f7323d61...,723ee62df289ce158a0faa4830844ce2dc375f38c1de36...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,0.0,...,"[1, 2, 3, 0]",0.0,0.0,2,1,"[2, 0, 3, 1]","[1, 2, 3, 0]",False,False,False
3032,3032,0,"[[[-18.94678497314453, False]], [[-40.43418884...","[[-18.94678497314453, False], [-40.43418884277...",none,"[acc, acc_norm]",f40958c221ca69b19026a2a2ce053da57c57f08254b152...,12884805bd68bf3cf91f42be7784dd80661d3d2b86e872...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1.0,...,"[0, 2, 3, 1]",1.0,1.0,0,0,"[0, 2, 3, 1]","[0, 2, 3, 1]",False,False,False
3033,3033,2,"[[[-24.67926788330078, False]], [[-20.71442794...","[[-24.67926788330078, False], [-20.71442794799...",none,"[acc, acc_norm]",dbeef71050b64e0a85ef4d362b36608c10939292ebb544...,27adbbb5a0b9f3aa53f1ed6e0f402556642493dd5b1d55...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1.0,...,"[2, 1, 0, 3]",0.0,1.0,1,2,"[1, 2, 3, 0]","[2, 1, 0, 3]",False,False,False
3034,3034,3,"[[[-22.328153610229492, False]], [[-43.6439247...","[[-22.328153610229492, False], [-43.6439247131...",none,"[acc, acc_norm]",0c380fb17fba9c6037249a0e4a8888f77f34687a5c5ef3...,b7feecd8efff107c2c4294d00f55a9077a6bf90fceb8e9...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,0.0,...,"[0, 3, 1, 2]",0.0,0.0,0,0,"[0, 3, 1, 2]","[0, 3, 1, 2]",False,False,False
3035,3035,0,"[[[-27.092754364013672, False]], [[-30.8680000...","[[-27.092754364013672, False], [-30.8680000305...",none,"[acc, acc_norm]",4aa4471f7a56a515df72c93b949ad40016299930c10c7e...,9031904dfa0a1ceaded5f7623b9bfff729a203a0424556...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1.0,...,"[0, 1, 3, 2]",1.0,1.0,0,0,"[0, 1, 2, 3]","[0, 1, 3, 2]",False,False,False

In [5]:

# Check that the model choices are consistent with accuracy, the label is called 'target'
assert all(
    (df_lm_eval_final_result['model_choice_init'] == df_lm_eval_final_result['target']) == (df_lm_eval_final_result['acc_init'] == 1)
), "Inconsistency found between model choices and accuracy in initial results."
assert all(
    (df_lm_eval_final_result['model_choice_final'] == df_lm_eval_final_result['target']) == (df_lm_eval_final_result['acc_final'] == 1)
), "Inconsistency found between model choices and accuracy in final results."

basic_performance_analysis(df_lm_eval_init_result)
basic_performance_analysis(df_lm_eval_final_result)

basic_performance_analysis(df_lm_eval_final_result, verdict_col_name="acc_final")
basic_performance_analysis(df_lm_eval_final_result, verdict_col_name="acc_init")

Overall Accuracy: 31.42% (954.0/3036)
Overall Accuracy: 44.66% (1356.0/3036)
Overall Accuracy: 44.66% (1356.0/3036)
Overall Accuracy: 31.42% (954.0/3036)

In [6]:
REPO_ID = "tomg-group-umd/fictionalqa_training_splits"
# LMEVAL_CONFIG_NAME = "fict_qa_obqa_blind_inf_ex_dedup_ds_mcq_topk4" alias
LMEVAL_CONFIG_NAME = "fict_qa_obqa_blind_inf_ex_dedup_ds_Llama-3-2-3B-Instruct_scored_rowlimNone_altlimNone_topk4_seed1234_slim"

df_hf_result = pull_raw_dataset(REPO_ID, LMEVAL_CONFIG_NAME)
# df_hf_result

In [7]:
# now join the two dataframes on index, they are the same order
df_merged_final = df_lm_eval_final_result.join(df_hf_result, lsuffix='_lm_eval', rsuffix='_hf')
# df_merged_final

In [8]:
# Add in the fictsheets and docs themselves

REPO_ID = "tomg-group-umd/fictionalqa"
CONFIG_NAME = "fictions"
df_fictions = pull_raw_dataset(REPO_ID, CONFIG_NAME)[["fiction_id","fiction"]]
CONFIG_NAME = "fictsheets"
df_fictsheets = pull_raw_dataset(REPO_ID, CONFIG_NAME)[["event_id","fictsheet"]]
CONFIG_NAME = "joined_qa"
df_joined_qa = pull_raw_dataset(REPO_ID, CONFIG_NAME)[["question_id","grade_informed","natural_answer_in_fiction"]]

df_merged_final = df_merged_final.merge(df_fictions, on="fiction_id", how="left").merge(
    df_fictsheets, on="event_id", how="left"
).merge(
    df_joined_qa, on="question_id", how="left"
)
# df_merged_final

In [9]:
# hand analysis columns

# for col in df_merged_final.columns:
#     print(f"\"{col}\",")

# cols_to_keep = [
#     # "doc_id",
#     # "target_lm_eval",
#     # "resps",
#     # "filtered_resps",
#     # "filter",
#     # "metrics",
#     # "doc_hash",
#     # "prompt_hash",
#     # "target_hash",
#     "acc",
#     # "acc_norm",
#     # "doc_event_id",
#     # "doc_fiction_id",
#     # "doc_question_id",
#     # "doc_span_answer",
#     # "doc_natural_answer",
#     # "doc_input",
#     # "doc_target",
#     # "doc_target_span",
#     # "doc_target_idx",
#     # "doc_topk_choices",
#     # "arguments_gen_args_0_arg_0",
#     # "arguments_gen_args_0_arg_1",
#     # "arguments_gen_args_1_arg_0",
#     # "arguments_gen_args_1_arg_1",
#     # "arguments_gen_args_2_arg_0",
#     # "arguments_gen_args_2_arg_1",
#     # "arguments_gen_args_3_arg_0",
#     # "arguments_gen_args_3_arg_1",
#     "event_id",
#     "fiction_id",
#     "question_id",
#     # "span_answer",
#     # "natural_answer",
#     "input",
#     "target_hf",
#     # "target_span",
#     "target_idx",
#     "topk_choices",
# ]
cols_to_keep = [
    "event_id",
    "fiction_id",
    "question_id",
    "fictsheet",
    "fiction",
    "input",
    "target_hf",
    "target_idx",
    "topk_choices",
    "choice_ranking_init",
    "choice_ranking_final",
    "W_and_E_in_choices",
    "W_and_E_is_model_choice_init",
    "W_and_E_is_model_choice_final",
    "model_choice_init",
    "model_choice_final",
    "acc_init",
    "acc_final",
    "grade_informed",
    "natural_answer_in_fiction",
]
df_merged_final = df_merged_final[cols_to_keep]

In [10]:
REPO_ID = "tomg-group-umd/fictionalqa_training_splits"
TRAIN_CONFIG_NAME = "event_split_fictions_webtext_train_ds_valratio0.33_seed1234_mcq_topk4"
VAL_CONFIG_NAME = "event_split_fictions_webtext_val_ds_valratio0.33_seed1234_mcq_topk4"

In [11]:
df_train = pull_raw_dataset(REPO_ID, TRAIN_CONFIG_NAME)
df_val = pull_raw_dataset(REPO_ID, VAL_CONFIG_NAME)
# df_train
# df_val

In [12]:
# basic_performance_analysis(df_lm_eval_final_result)
# basic_performance_analysis(df_merged_final)

In [13]:
df_merged_final_train = df_merged_final[df_merged_final['fiction_id'].isin(df_train['fiction_id'])]
print("Train Set Performance:")
basic_performance_analysis(df_merged_final_train, verdict_col_name="acc_init")
basic_performance_analysis(df_merged_final_train, verdict_col_name="acc_final")

Train Set Performance:
Overall Accuracy: 31.91% (633.0/1984)
Overall Accuracy: 45.31% (899.0/1984)

In [14]:
df_merged_final_val = df_merged_final[df_merged_final['fiction_id'].isin(df_val['fiction_id'])]
print("Validation Set Performance:")
basic_performance_analysis(df_merged_final_val, verdict_col_name="acc_init")
basic_performance_analysis(df_merged_final_val, verdict_col_name="acc_final")

Validation Set Performance:
Overall Accuracy: 30.51% (321.0/1052)
Overall Accuracy: 43.44% (457.0/1052)

In [15]:
# df_merged_final

In [16]:
# df_merged_final_train

In [17]:
# df_merged_final_val

In [18]:
# compute some confusion matrix like stats
# df_for_stats = df_merged_final
# df_for_stats = df_merged_final_train
df_for_stats = df_merged_final_val

# df_for_stats = df_for_stats.drop_duplicates(subset=['target_hf'], keep='first')
# df_for_stats = df_for_stats.drop_duplicates(subset=['target_hf'], keep='last')

# eg. fraction of rows whose acc_init was 1 that also have acc_final 1
num_init_correct = df_for_stats[df_for_stats['acc_init'] == 1].shape[0]
num_init_and_final_correct = df_for_stats[(df_for_stats['acc_init'] == 1) & (df_for_stats['acc_final'] == 1)].shape[0]
fraction_init_correct_final_correct = num_init_and_final_correct / num_init_correct if num_init_correct > 0 else 0
print(f"Fraction of initially correct answers that still remained correct after training: {fraction_init_correct_final_correct:.2%} ({num_init_and_final_correct}/{num_init_correct})")

# or fraction of final correct answers that were novel, i.e. not in initially correct
num_final_correct = df_for_stats[df_for_stats['acc_final'] == 1].shape[0]
num_final_novel_correct = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 1)].shape[0]
fraction_final_novel_correct = num_final_novel_correct / num_final_correct if num_final_correct > 0 else 0
print(f"Fraction of final correct answers that were learned i.e. not initially correct: {fraction_final_novel_correct:.2%} ({num_final_novel_correct}/{num_final_correct})")

# fraction that were final correct and novel, and also had a grade_informed of 1
num_final_novel_correct_with_grade_informed = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 1) & (df_for_stats['grade_informed'] == 1)].shape[0]
fraction_final_novel_correct_with_grade_informed = num_final_novel_correct_with_grade_informed / num_final_novel_correct if num_final_novel_correct > 0 else 0
print(f"Fraction of learned questions that also had grade_informed=1: {fraction_final_novel_correct_with_grade_informed:.2%} ({num_final_novel_correct_with_grade_informed}/{num_final_novel_correct})")

# fraction of questions that could be learned, i.e. were initially incorrect, and then became correct
num_learnable = df_for_stats[(df_for_stats['acc_init'] == 0)].shape[0]
num_learned = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 1)].shape[0]
fraction_learned = num_learned / num_learnable if num_learnable > 0 else 0
print(f"Fraction of learnable questions (initially incorrect) that were learned: {fraction_learned:.2%} ({num_learned}/{num_learnable})") 

# fraction of learned questions where "natural_answer_in_fiction" is 1
num_learned_with_natural_answer_in_fiction = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 1) & (df_for_stats['natural_answer_in_fiction'] == 1)].shape[0]
fraction_learned_with_natural_answer_in_fiction = num_learned_with_natural_answer_in_fiction / num_learned if num_learned > 0 else 0
print(f"Fraction of learned questions where natural_answer_in_fiction==1: {fraction_learned_with_natural_answer_in_fiction:.2%} ({num_learned_with_natural_answer_in_fiction}/{num_learned})")

# fraction of questions learnable but model failed to learn where "natural_answer_in_fiction" is 1
num_not_learned_with_natural_answer_in_fiction = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 0) & (df_for_stats['natural_answer_in_fiction'] == 1)].shape[0]
num_not_learned = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 0)].shape[0]
fraction_not_learned_with_natural_answer_in_fiction = num_not_learned_with_natural_answer_in_fiction / num_not_learned if num_not_learned > 0 else 0
print(f"Fraction of questions that model could have learned but did not where natural_answer_in_fiction==1: {fraction_not_learned_with_natural_answer_in_fiction:.2%} ({num_not_learned_with_natural_answer_in_fiction}/{num_not_learned})")

# other way around, for questions where natural_answer_in_fiction is 1, what fraction were learned vs possible to learn
num_learnable_with_natural_answer_in_fiction = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['natural_answer_in_fiction'] == 1)].shape[0]
fraction_learned_with_natural_answer_in_fiction = num_learned_with_natural_answer_in_fiction / num_learnable_with_natural_answer_in_fiction if num_learnable_with_natural_answer_in_fiction > 0 else 0
print(f"Fraction of learnable questions where natural_answer_in_fiction==1 that were actually learned: {fraction_learned_with_natural_answer_in_fiction:.2%} ({num_learned_with_natural_answer_in_fiction}/{num_learnable_with_natural_answer_in_fiction})")

# then for questions where natural_answer_in_fiction is 0, what fraction were learned vs possible to learn
num_learnable_with_natural_answer_not_in_fiction = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['natural_answer_in_fiction'] == 0)].shape[0]
num_learned_with_natural_answer_not_in_fiction = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 1) & (df_for_stats['natural_answer_in_fiction'] == 0)].shape[0]
fraction_learned_with_natural_answer_not_in_fiction = num_learned_with_natural_answer_not_in_fiction / num_learnable_with_natural_answer_not_in_fiction if num_learnable_with_natural_answer_not_in_fiction > 0 else 0
print(f"Fraction of learnable questions where natural_answer_in_fiction==0 that were actually learned: {fraction_learned_with_natural_answer_not_in_fiction:.2%} ({num_learned_with_natural_answer_not_in_fiction}/{num_learnable_with_natural_answer_not_in_fiction})")


# fraction with W and E as a choice
num_with_W_and_E_choice = df_for_stats[df_for_stats['W_and_E_in_choices'] == True].shape[0]
fraction_with_W_and_E_choice = num_with_W_and_E_choice / df_for_stats.shape[0] if df_for_stats.shape[0] > 0 else 0
print(f"Fraction of samples with 'W and E' as a choice: {fraction_with_W_and_E_choice:.2%} ({num_with_W_and_E_choice}/{df_for_stats.shape[0]})")

# or fraction of acquired final correct answers that had W and E as first choice initially, but then didnt and were 
num_final_correct_novel = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 1)].shape[0]
num_final_novel_W_and_E_demoted_correct = df_for_stats[(df_for_stats['acc_init'] == 0) & (df_for_stats['acc_final'] == 1) & (df_for_stats['W_and_E_is_model_choice_init'] == 1) & (df_for_stats['W_and_E_is_model_choice_final'] == 0)].shape[0]
fraction_final_novel_W_and_E_demoted_correct = num_final_novel_W_and_E_demoted_correct / num_final_correct_novel if num_final_correct_novel > 0 else 0
print(f"Fraction of learned questions that had 'W and E' as initial model choice but then demoted it: {fraction_final_novel_W_and_E_demoted_correct:.2%} ({num_final_novel_W_and_E_demoted_correct}/{num_final_correct_novel})")

# acquired correct questions after ignoring the W and E demotion cases, as a fraction questions that could be learned ignoring W and E demotion cases
num_final_novel_ignoring_W_and_E_demoted = num_final_novel_correct - num_final_novel_W_and_E_demoted_correct
num_learnable_ignoring_W_and_E_demoted = num_learnable - num_final_novel_W_and_E_demoted_correct
fraction_learned_ignoring_W_and_E_demoted = num_final_novel_ignoring_W_and_E_demoted / num_learnable_ignoring_W_and_E_demoted if num_learnable_ignoring_W_and_E_demoted > 0 else 0
print(f"Fraction of learnable questions that were learned ignoring W and E demotion cases: {fraction_learned_ignoring_W_and_E_demoted:.2%} ({num_final_novel_ignoring_W_and_E_demoted}/{num_learnable_ignoring_W_and_E_demoted})")

Fraction of initially correct answers that still remained correct after training: 85.36% (274/321)
Fraction of final correct answers that were learned i.e. not initially correct: 40.04% (183/457)
Fraction of learned questions that also had grade_informed=1: 89.62% (164/183)
Fraction of learnable questions (initially incorrect) that were learned: 25.03% (183/731)
Fraction of learned questions where natural_answer_in_fiction==1: 83.06% (152/183)
Fraction of questions that model could have learned but did not where natural_answer_in_fiction==1: 58.94% (323/548)
Fraction of learnable questions where natural_answer_in_fiction==1 that were actually learned: 32.00% (152/475)
Fraction of learnable questions where natural_answer_in_fiction==0 that were actually learned: 12.11% (31/256)
Fraction of samples with 'W and E' as a choice: 32.41% (341/1052)
Fraction of learned questions that had 'W and E' as initial model choice but then demoted it: 29.51% (54/183)
Fraction of learnable questions that were learned ignoring W and E demotion cases: 19.05% (129/677)

In [19]:
import spacy

# Load a larger spaCy model for better NER performance
# try:
#     nlp = spacy.load("en_core_web_sm")
# except OSError:
#     print("Downloading 'en_core_web_sm' model. This may take a moment.")
#     spacy.cli.download("en_core_web_sm")
#     nlp = spacy.load("en_core_web_sm")

nlp = spacy.load("en_core_web_sm")
# nlp = spacy.load("en_core_web_lg")

def calculate_distributional_overlap(
    col1: pd.Series,
    col2: pd.Series
) -> dict:
    """
    Measures the overlap between the entire contents of two string columns
    from a DataFrame using Jaccard Similarity on:
    1. Named Entities (using spaCy NER)
    2. All unique words (tokens).

    Args:
        col1: The first pandas Series (string column).
        col2: The second pandas Series (string column).

    Returns:
        A dictionary containing the calculated Jaccard Similarity measures.
    """

    # --- 1. Aggregate and Process Text ---

    # Concatenate all text in each column into a single large string
    # but shuffle before joining to avoid any order effects
    # col1 = col1.sample(frac=1, random_state=42).reset_index(drop=True)
    # col2 = col2.sample(frac=1, random_state=42).reset_index(drop=True)

    # text1_raw = " ".join(col1.astype(str))
    # text2_raw = " ".join(col2.astype(str))
    # using a newline sep to try and break up any accidental n-grams across rows
    # text1_raw = "\n".join(col1.astype(str))
    # text2_raw = "\n".join(col2.astype(str))

    # nah, best to create lists of ents per col and word by looping
    # --- 1.1 Process Text ---

    print("Processing text with spaCy, this may take a while...")
    # Process the aggregated text with spaCy
    # doc1 = nlp(text1_raw)
    # doc2 = nlp(text2_raw)
    docs_1 = list(nlp.pipe(col1.astype(str).tolist(), n_process=32))
    print("Text processing for col1 complete!")
    docs_2 = list(nlp.pipe(col2.astype(str).tolist(), n_process=32))
    print("Text processing for col2 complete!")

    # --- 2. Calculate Named Entity Jaccard Similarity ---

    # Extract all unique named entity strings (e.g., 'Apple Inc.', 'London')
    # from the entire content of each column.
    # entities1 = set([ent.text.lower() for ent in doc1.ents])
    # entities2 = set([ent.text.lower() for ent in doc2.ents])
    entities1 = set([ent.text.lower() for doc in docs_1 for ent in doc.ents])
    entities2 = set([ent.text.lower() for doc in docs_2 for ent in doc.ents])

    # Jaccard Similarity (Intersection / Union)
    # 
    entity_intersection = len(entities1.intersection(entities2))
    entity_union = len(entities1.union(entities2))

    # Avoid division by zero if both sets are empty
    entity_jaccard_similarity = (
        entity_intersection / entity_union if entity_union > 0 else 0.0
    )

    # --- 3. Calculate Word (Token) Jaccard Similarity ---

    # Extract all unique lowercased, non-punctuation, non-stopword tokens
    # (a basic form of distributional feature).
    # words1 = set([
    #     token.text.lower()
    #     for token in doc1
    #     if not token.is_punct and not token.is_space and not token.is_stop
    # ])
    # words2 = set([
    #     token.text.lower()
    #     for token in doc2
    #     if not token.is_punct and not token.is_space and not token.is_stop
    # ])
    words1 = set([
        token.text.lower()
        for doc in docs_1
        for token in doc
        if not token.is_punct and not token.is_space and not token.is_stop
    ])
    words2 = set([
        token.text.lower()
        for doc in docs_2
        for token in doc
        if not token.is_punct and not token.is_space and not token.is_stop
    ])

    word_intersection = len(words1.intersection(words2))
    word_union = len(words1.union(words2))

    word_jaccard_similarity = (
        word_intersection / word_union if word_union > 0 else 0.0
    )

    # --- 4. Conceptual ROUGE Note ---

    # For a ROUGE-like n-gram overlap measure:
    # ROUGE is typically used for sequence-to-sequence comparison (summary vs. reference).
    # To apply it here, you would treat `text1_raw` as the 'reference' and `text2_raw`
    # as the 'summary' and use a dedicated library like `rouge-score` or `py-rouge`.
    # A simple n-gram overlap is captured conceptually by the Word Jaccard (using unigrams).

    # --- 5. Return Results ---

    return {
        "entity_jaccard_similarity": entity_jaccard_similarity,
        "word_jaccard_similarity": word_jaccard_similarity,
        "entities_col1_count": len(entities1),
        "entities_col2_count": len(entities2),
        "words_col1_count": len(words1),
        "words_col2_count": len(words2),
        "entities_set_col1": entities1,
        "entities_set_col2": entities2,
        "words_set_col1": words1,
        "words_set_col2": words2,
    }

In [20]:
# there are two sets train and val, and two conditions init and final, which can either be 1 or 0, so there are 8 possible subsets
overlap_train_df = df_merged_final_train[(df_merged_final_train['acc_init'] == 0) & (df_merged_final_train['acc_final'] == 0)]
overlap_val_df = df_merged_final_val[(df_merged_final_val['acc_init'] == 0) & (df_merged_final_val['acc_final'] == 0)]
# # ...
# overlap_train_df = df_merged_final_train[(df_merged_final_train['acc_init'] == 1) & (df_merged_final_train['acc_final'] == 1)]
# overlap_val_df = df_merged_final_val[(df_merged_final_val['acc_init'] == 1) & (df_merged_final_val['acc_final'] == 1)]


calculate_distributional_overlap(
    overlap_train_df['target_hf'],
    overlap_val_df['target_hf']
)

Processing text with spaCy, this may take a while...

Text processing for col1 complete!
Text processing for col2 complete!

{'entity_jaccard_similarity': 0.017595307917888565,
 'word_jaccard_similarity': 0.10522496371552975,
 'entities_col1_count': 224,
 'entities_col2_count': 123,
 'words_col1_count': 936,
 'words_col2_count': 587,
 'entities_set_col1': {'1951',
  '1957',
  '1960s',
  '1961',
  '1962',
  '1986',
  '2004',
  '2021',
  '2047',
  '2054',
  '30-foot',
  '70',
  'acoustic',
  'acoustic technologies',
  'ai',
  'aiden cross',
  'amelia chen',
  'anabelle johnson',
  'angel of salisbury street',
  'annual',
  'april 2003',
  'arjun kohli',
  'armpit hair styling',
  'art collective',
  'arthur silvers',
  'ashwick anomaly research group',
  "beatrice clemens'",
  'beijing',
  'berlin',
  'britain',
  'buenos aires',
  'california',
  'cambridge',
  'cambridge collaborative writing festival',
  'carson whitmore',
  'carsonville',
  'carsonville forest',
  'carsonville local authorities',
  'carsonville research institute',
  'celtic',
  'centre pompidou',
  'coastal acoustic research institute',
  'cummerbund craze',
  "cummerbund craze'",
  'custard heist',
  'darwish',
  'data-consciousness ethics',
  'department of defense',
  'digital',
  'digital guardians',
  'digital security',
  'early 1908',
  'early 1910s',
  'early 1950s',
  'early 2014',
  'eco-symbiosis conference',
  'eiffel tower',
  'elara kumar',
  'eldermont',
  'eldermont culinary festival',
  'eldermont hamburger festival',
  'eldridge park',
  'eleanor pierce',
  'elisa baum',
  'english',
  'ernest carruthers',
  "establisher's",
  'ethan tchaikovsky',
  'evelyn sanderson',
  'fbi',
  'finley flour fest',
  'flavorsync ai',
  'flour tattoo artists collective',
  'forelimb',
  'french',
  'general store',
  'genetics organization',
  'geneva',
  'glenbrook',
  'global botanical society',
  'global ethics',
  'global marlines',
  'global tech summit',
  'greenery',
  'greenfield',
  'guild',
  'hamburger witch trials',
  'hanna simms',
  'harberds',
  'harland',
  'harmonia springs',
  'harpooner',
  'harriet langston',
  'hearthville',
  'helen macintyre',
  'home of unity culinary arts',
  'hound-mule relay event',
  'hound-mules',
  'hubert blystone',
  'iceas',
  'imarc',
  'inclusive urban farm movement',
  'industrial guild of traditional manufacturers',
  'international environmental summit',
  'international satire artists coalition',
  'klein & foster marketing',
  'kliffonia village council',
  'kumquat hybrid',
  'langston',
  'langston hall',
  'langston reformation',
  'langston reformation committee',
  'larkson',
  'late 2021',
  'late 2054',
  'lenny marsh',
  'liam fulton',
  'lila manning',
  'lila trenton',
  'lillian montgomery',
  'linda periwinkle',
  'linnea rodriguez',
  'logic route council',
  'lost society of grimswood',
  'lucas vernon',
  'lucy atwater',
  'ludlow springs',
  'ludlow springs gazette',
  'lunch break revolution',
  'lunchrooms',
  'macintyre',
  'manchester city center',
  'manchester society',
  'marcus harlan',
  'margaret pritchard',
  'mediterranean security consortium',
  'mesenchyme muffins',
  'mesenchyme music mystery',
  'mid-2014',
  'mid-2021',
  'mid-2045',
  'midnight stag society',
  'millstone museum',
  'mitch tomlinson',
  'montgomery police department',
  'montgomery yoyo competition series',
  'museum of time',
  "museum of time' festival",
  'national dessert association',
  'national manufacturing ethics committee',
  'national psychology association',
  'native american',
  'neo-politan',
  'new cambridge',
  'new cambridge enlightenment society',
  'new carson regulatory body',
  'new chicago',
  'notre-dame',
  'oscar yates',
  'overnight',
  'overnight steeple',
  'paris',
  'pine crest',
  'pulley system',
  'reader feedback',
  'renée fournier',
  'richard greyson',
  'robert caldwell',
  'rosemary callahan',
  'royal manchester theater',
  'sahara cryptography society',
  'san francisco',
  'sanderson institute for genetic excellence',
  'sandville',
  'sandville health department',
  'sandville unified school',
  'silicon city',
  'silicon valley',
  'soap',
  'society for auditory preservation',
  'soul harmony',
  'soundcorp',
  'soundfest',
  'soundville',
  'spring 1907',
  'summer 1957',
  'susie trenton',
  'switzerland',
  'synesthesia',
  'temporal truth seekers',
  'ten-year-old',
  'texas',
  'the bowling cart capital',
  'the cummerbund capital',
  'the great sphinx',
  "the great war's",
  'the great yoyo yowl',
  'the green lantern',
  'the international art collective',
  'the lunch break revolution',
  'the mysterious forelimb',
  'the mysterious forelimb fossil',
  'the mysterious overnight steeple phenomenon',
  'the nocturnal canvas',
  'the performing arts',
  'the pie festival',
  'the pinafore society',
  'the psychedelic hour incident',
  'the secret society of aten',
  'the slap heard around',
  'the yoyo association scandal',
  'thomas larkin',
  'thomas wainwright',
  'timothy abbott',
  'tokyo',
  'trophy case',
  'unsuitable custard-like',
  'ventriloquy',
  "von adler's",
  'wellbrook',
  'wicklow conservation council',
  'willow junction',
  'windwhistle coastal art festival',
  'wisconsin'},
 'entities_set_col2': {'1910',
  '1928',
  '1946',
  '1951',
  '1982',
  '1988',
  '2042',
  '2059',
  '2062',
  'acoustics guild',
  'acrylite subgroup uprising',
  'alana cheng',
  'alcina',
  'algae',
  'algeria',
  'ambleton cultural heritage fund',
  'arizona',
  'arizonans',
  'ashford museum',
  'autumn 1963',
  'belgium',
  'bernard thrush',
  'birchtown folklore society',
  'british ministry of communications',
  'brussels',
  'circle',
  'clara mckinley',
  'creative athletics society',
  'crestwood symposium on immunology',
  'david wexler',
  'decrypt task force',
  'early settler days',
  'eastern',
  'edith granger',
  'egypt',
  'el águila',
  'eliza thompson',
  'embarcadero',
  'ethical game development',
  'fcc',
  'february 2060',
  'federal communications commission',
  'fiskville',
  'fiskville fisheries convention',
  'fiskville renewable energy research facility',
  'flavia',
  'flour fields',
  'france',
  'future of entertainment technology',
  'gamy',
  'geological institute',
  'grainsville',
  'greentech',
  'harold bell',
  'harold livingston',
  'hiroshi kato',
  'horatio lindholm',
  'ifoc',
  'ingrid nilsen',
  'international conference on communication technology',
  'international cryptology conference',
  'international financial oversight committee',
  'isabella morales',
  'james hallman',
  'james hawthorne',
  'january 2040',
  'jasmine lin',
  'jason moorland',
  'javier mendoza',
  'june 1906',
  'leopold von strauss',
  'lila harrington',
  'lin family bakery',
  'linda carver',
  'lucas',
  'ludlow springs',
  'march 4, 1936',
  'matilda groves',
  'meander square',
  'misdelivery of micro-drones',
  'morocco',
  'mystic',
  'napkin',
  'national health convention',
  'national health convention of',
  'neo-bristol square',
  'new amsterdalia',
  'new york',
  'norse',
  'norse historians association',
  'north africa',
  'oliver stone',
  'paris',
  'railing studios',
  'reflective music-box treaty',
  'reversed falls',
  'richard greyson',
  'rio de janeiro',
  'salt chasm',
  'san francisco',
  'san francisco city council',
  'scientific renaissance',
  'september 2040',
  'shoe-horn',
  'south korean',
  'stockholm',
  'strawberry milkshake',
  'sydney',
  'the acoustics guild',
  "the cheddar club's",
  'the great cheddar convention',
  'the immune valley',
  'the new grain capital',
  'the silent abbott',
  'theo reynolds',
  'thomas bright',
  'thrush',
  'tokyo',
  'vienna',
  'waterfall whisper',
  'western',
  'western alps',
  'winslow geological institute'},
 'words_set_col1': {'1907',
  '1908',
  '1910s',
  '1950s',
  '1951',
  '1957',
  '1960s',
  '1961',
  '1962',
  '1986',
  '2003',
  '2004',
  '2014',
  '2021',
  '2022',
  '2047',
  '2054',
  '30',
  '70',
  'abandoned',
  'abbott',
  'absorbing',
  'acceptance',
  'access',
  'acclaim',
  'accord',
  'accountability',
  'acoustic',
  'acoustics',
  'act',
  'adler',
  'adrenaline',
  'advanced',
  'advancements',
  'advertising',
  'advice',
  'advocacy',
  'age',
  'agriculture',
  'ai',
  'aiden',
  'aires',
  'algorithms',
  'amateur',
  'ambient',
  'amelia',
  'american',
  'anabelle',
  'analysis',
  'ancient',
  'angel',
  'annual',
  'anomaly',
  'aphrodisiac',
  'apparatus',
  'appear',
  'appreciation',
  'april',
  'arcade',
  'archaeological',
  'architect',
  'architectural',
  'areas',
  'arjun',
  'armpit',
  'art',
  'arthur',
  'artifacts',
  'artisans',
  'artistic',
  'artists',
  'arts',
  'ashbrook',
  'ashwick',
  'assess',
  'association',
  'aten',
  'attention',
  'atwater',
  'auditory',
  'authorities',
  'authorship',
  'automated',
  'autonomy',
  'autumn',
  'avian',
  'award',
  'backyard',
  'balance',
  'basic',
  'bass',
  'baum',
  'beans',
  'beatrice',
  'begonia',
  'beijing',
  'beneath',
  'benefits',
  'berlin',
  'best',
  'bill',
  'binoculars',
  'bioluminescent',
  'bird',
  'birdwatchers',
  'birthplace',
  'blooming',
  'blystone',
  'body',
  'boom',
  'boost',
  'boosted',
  'botanical',
  'botanists',
  'boundaries',
  'bowling',
  'box',
  'boy',
  'brackets',
  'break',
  'britain',
  'brow',
  'buenos',
  'burial',
  'butcher',
  'cache',
  'cafes',
  'caldwell',
  'california',
  'callahan',
  'cambridge',
  'candles',
  'canvas',
  'capabilities',
  'capital',
  'caricatures',
  'carruthers',
  'carson',
  'carsonville',
  'cart',
  'carts',
  'carvings',
  'case',
  'cd',
  'cellar',
  'celtic',
  'center',
  'centre',
  'changes',
  'chapel',
  'checks',
  'cheesecake',
  'chefs',
  'chemistry',
  'chen',
  'chicago',
  'chocolate',
  'cholesterol',
  'choreography',
  'city',
  'clemens',
  'clinics',
  'coalition',
  'coastal',
  'cocoon',
  'coffee',
  'cold',
  'collaboration',
  'collaborative',
  'collective',
  'committee',
  'common',
  'communal',
  'communication',
  'communities',
  'community',
  'competition',
  'competitions',
  'composition',
  'computational',
  'computer',
  'computing',
  'concepts',
  'conditions',
  'conference',
  'conferences',
  'consciousness',
  'conservation',
  'consortium',
  'conspiracy',
  'construction',
  'contaminated',
  'content',
  'contest',
  'controversial',
  'conventions',
  'conviction',
  'cooking',
  'corporate',
  'correction',
  'council',
  'countryside',
  'courbet',
  'courtyards',
  'craze',
  'cream',
  'creations',
  'creative',
  'crest',
  'cross',
  'cryptography',
  'culinary',
  'cultural',
  'cummerbund',
  'curious',
  'curriculum',
  'custard',
  'customization',
  'dame',
  'dance',
  'darwish',
  'data',
  'debate',
  'debates',
  'debugged',
  'decision',
  'decryption',
  'default',
  'defense',
  'demand',
  'demands',
  'department',
  'desolation',
  'dessert',
  'destination',
  'detainment',
  'detection',
  'detective',
  'devastate',
  'dialogue',
  'digital',
  'dilution',
  'diplomacy',
  'discovery',
  'discussions',
  'diseases',
  'dispensers',
  'dissecting',
  'doctorate',
  'dormant',
  'dr.',
  'dreams',
  'driven',
  'drones',
  'dwindling',
  'dyes',
  'dynamic',
  'early',
  'eccentric',
  'echoes',
  'eco',
  'ecological',
  'economic',
  'economy',
  'ecosystem',
  'ecovillage',
  'ecovillages',
  'ecumenical',
  'effect',
  'eiffel',
  'elaborate',
  'elara',
  'eldermont',
  'eldridge',
  'eleanor',
  'elevate',
  'elisa',
  'emotional',
  'encounter',
  'encrypted',
  'end',
  'engineer',
  'engineering',
  'english',
  'enhanced',
  'enlightenment',
  'ensemble',
  'ensure',
  'entity',
  'environmental',
  'environmentalists',
  'ephemeral',
  'ernest',
  'establisher',
  'ethan',
  'ethical',
  'ethics',
  'evaluate',
  'evelyn',
  'event',
  'eviction',
  'evil',
  'excavations',
  'excellence',
  'exhibit',
  'exhibition',
  'experiment',
  'experimental',
  'explanation',
  'expressions',
  'exquisite',
  'extensive',
  'fair',
  'famous',
  'farm',
  'faulty',
  'fbi',
  'feather',
  'federal',
  'feedback',
  'fest',
  'festival',
  'festivals',
  'fiberglass',
  'fictional',
  'finesse',
  'finley',
  'fire',
  'flaky',
  'flatline',
  'flavorsync',
  'flip',
  'floorboards',
  'flops',
  'flour',
  'flowcharts',
  'flu',
  'folklore',
  'food',
  'foot',
  'foreign',
  'forelimb',
  'forest',
  'forgotten',
  'formations',
  'fossil',
  'foster',
  'fournier',
  'francisco',
  'freedoms',
  'french',
  'frequency',
  'fulton',
  'fusion',
  'future',
  'gained',
  'gardens',
  'garment',
  'gateways',
  'gathering',
  'gazette',
  'general',
  'genetic',
  'genetics',
  'geneva',
  'glenbrook',
  'global',
  'globally',
  'goods',
  'gourmet',
  'government',
  'grants',
  'great',
  'green',
  'greenery',
  'greenfield',
  'greenhaven',
  'greyhound',
  'greyson',
  'grimswood',
  'group',
  'groups',
  'growth',
  'guardians',
  'guidelines',
  'guild',
  'hair',
  'hall',
  'hallucinations',
  'hamburger',
  'hanna',
  'harberds',
  'harlan',
  'harland',
  'harmonia',
  'harmony',
  'harpooner',
  'harriet',
  'health',
  'heard',
  'hearthville',
  'heightened',
  'heist',
  'helen',
  'hieroglyphics',
  'historical',
  'history',
  'hoax',
  'home',
  'honor',
  'hotspot',
  'hound',
  'hour',
  'household',
  'hub',
  'hubert',
  'hubs',
  'human',
  'hybrid',
  'ice',
  'iceas',
  'illegal',
  'illusion',
  'imarc',
  'impact',
  'improvement',
  'incident',
  'inclusive',
  'incomplete',
  'increase',
  'increased',
  'individual',
  'industrial',
  'infused',
  'ingenuity',
  'initiative',
  'initiatives',
  'innovation',
  'innovations',
  'innovative',
  'inquiry',
  'inside',
  'insights',
  'inspired',
  'institute',
  'integration',
  'intelligent',
  'intentions',
  'interaction',
  'interactions',
  'interest',
  'international',
  'interwar',
  'intricate',
  'intrigue',
  'investigate',
  'item',
  'johnson',
  'junction',
  'jungle',
  'kimono',
  'klein',
  'kliffonia',
  'kohli',
  'kumar',
  'kumquat',
  'labor',
  'laboratory',
  'land',
  'landfills',
  'landmark',
  'landmarks',
  'lanes',
  'langston',
  'lantern',
  'larkin',
  'larkson',
  'late',
  'law',
  'legacy',
  'legume',
  'legumes',
  'lemonade',
  'lenny',
  'liam',
  'liberation',
  'libraries',
  'library',
  'life',
  'light',
  'lighter',
  'lighthouse',
  'lights',
  'like',
  'lila',
  'lillian',
  'linda',
  'linnea',
  'lintown',
  'living',
  'local',
  'logic',
  'lost',
  'lotion',
  'louvre',
  'low',
  'lucas',
  'lucy',
  'ludlow',
  'lumberjacks',
  'lunch',
  'lunchrooms',
  'lush',
  'macintyre',
  'maestro',
  'major',
  'making',
  'manchester',
  'mandatory',
  'manifestations',
  'manipulation',
  'manning',
  'manufacturers',
  'manufacturing',
  'marcus',
  'margaret',
  'marine',
  'maritime',
  'marketing',
  'marlines',
  'marsh',
  'marv',
  'materials',
  'meals',
  'measures',
  'mechanical',
  'mechanism',
  'medallion',
  'mediterranean',
  'meeting',
  'melody',
  'membership',
  'mesenchyme',
  'message',
  'methodologies',
  'mid-1960s',
  'mid-2014',
  'mid-2021',
  'mid-2045',
  'midnight',
  'millstone',
  'minerals',
  'missing',
  'mitch',
  'moat',
  'modern',
  'mogul',
  'moguls',
  'monitoring',
  'montgomery',
  'mound',
  'mounted',
  'mouthpiece',
  'movement',
  'movements',
  'muffins',
  'mule',
  'mules',
  'mundane',
  'mural',
  'muse',
  'museum',
  'music',
  'musician',
  'mutated',
  'mysteries',
  'mysterious',
  'mystery',
  'national',
  'nationwide',
  'native',
  'natural',
  'neglected',
  'neighboring',
  'neo',
  'new',
  'nexus',
  'nocturnal',
  'noise',
  'nostalgic',
  'notre',
  'nucleotide',
  'oasis',
  'oboe',
  'obsession',
  'officer',
  'old',
  'operatic',
  'operatives',
  'optical',
  'organization',
  'ornate',
  'oscar',
  'osteopath',
  'otherworldly',
  'outbreak',
  'outcry',
  'outdated',
  'overnight',
  'pact',
  'painted',
  'paleontology',
  'paradigm',
  'parenthesis',
  'paris',
  'park',
  'past',
  'paste',
  'patterns',
  'peace',
  'perception',
  'performance',
  'performing',
  'periwinkle',
  'personal',
  'phenomena',
  'phenomenon',
  'photographs',
  'pie',
  'pierce',
  'pilgrimage',
  'pinafore',
  'pine',
  'places',
  'planning',
  'plant',
  'police',
  'policies',
  'policy',
  'politan',
  'politics',
  'pompidou',
  'portrait',
  'posture',
  'powered',
  'practical',
  'precincts',
  'preservation',
  'president',
  'principles',
  'pritchard',
  'privacy',
  'prize',
  'problems',
  'production',
  'professor',
  'programmers',
  'projections',
  'projects',
  'properties',
  'protective',
  'protests',
  'protocols',
  'pseudocode',
  'psychedelic',
  'psychological',
  'psychology',
  'public',
  'pulley',
  'quarters',
  'radical',
  'raised',
  'rare',
  'reader',
  'readers',
  'reducing',
  'reef',
  'reevaluation',
  'reform',
  'reformation',
  'reforms',
  'regions',
  'regulation',
  'regulations',
  'regulatory',
  'related',
  'relay',
  'relic',
  'relics',
  'renaissance',
  'renowned',
  'renée',
  'replaced',
  'replacement',
  'replica',
  'reproduced',
  'research',
  'researchers',
  'residents',
  'resilience',
  'respected',
  'restricted',
  'resurgence',
  'rethink',
  'retired',
  'revised',
  'revisions',
  'revitalized',
  'revolution',
  'revolutionize',
  'richard',
  'ring',
  'rise',
  'rituals',
  'road',
  'robert',
  'rodriguez',
  'role',
  'rosemary',
  'route',
  'royal',
  'rule',
  'rules',
  'rumors',
  'rushes',
  'safety',
  'sahara',
  'sales',
  'salisbury',
  'salon',
  'san',
  'sanderson',
  'sandville',
  'satire',
  'sauce',
  'scandal',
  'school',
  'science',
  'scientific',
  'scientists',
  'script',
  'scrubbing',
  'secret',
  'security',
  'seeds',
  'seekers',
  'segment',
  'selim',
  'sender',
  'senses',
  'septicaemia',
  'sequences',
  'series',
  'service',
  'settlement',
  'sheet',
  'shift',
  'shifts',
  'ship',
  'siblings',
  'signals',
  'significant',
  'signs',
  'silence',
  'silicon',
  'silver',
  'silvers',
  'similar',
  'simms',
  'site',
  'skepticism',
  'slap',
  'soap',
  'society',
  'soil',
  'solar',
  'song',
  'sorrowful',
  'soul',
  'sound',
  'soundcorp',
  'soundfest',
  'sounds',
  'soundscapes',
  'soundville',
  'spaces',
  'special',
  'species',
  'specific',
  'speed',
  'sphinx',
  'spirit',
  'spirits',
  'spring',
  'springs',
  'square',
  'stabilization',
  'stag',
  'stamina',
  'stand',
  'standards',
  'statewide',
  'statue',
  'steam',
  'steeple',
  'step',
  'stewardship',
  'stopwatch',
  'store',
  'strain',
  'strategies',
  'strategy',
  'street',
  'stricter',
  'structure',
  'study',
  'styling',
  'subroutine',
  'success',
  'suffragette',
  'summer',
  'summit',
  'summon',
  'supply',
  'surge',
  'susie',
  'suspension',
  'sustainable',
  'sweatshop',
  'switzerland',
  'symbiosis',
  'symphony',
  'symposium',
  'synesthesia',
  'synesthetic',
  'system',
  'talking',
  'tattoo',
  'tchaikovsky',
  'tech',
  'techniques',
  'technological',
  'technologies',
  'technology',
  'temporal',
  'temporary',
  'tethering',
  'texas',
  'theater',
  'therapy',
  'thistle',
  'thomas',
  'time',
  'timekeeping',
  'timothy',
  'tokyo',
  'tomlinson',
  'tools',
  'toured',
  'tourism',
  'tower',
  'towering',
  'town',
  'towns',
  'tradition',
  'traditional',
  'traditions',
  'transcended',
  'transformation',
  'travel',
  'tremors',
  'trend',
  'trenton',
  'trials',
  'trick',
  'tritone',
  'trophy',
  'truth',
  'typical',
  'unbiased',
  'unconventional',
  'unified',
  'unity',
  'unknown',
  'unrecorded',
  'unsolved',
  'unsuitable',
  'unverified',
  'uprising',
  'urban',
  'urn',
  'usage',
  'use',
  'valley',
  'valuable',
  'vary',
  'ventriloquists',
  'ventriloquy',
  'vernon',
  'vibrations',
  'village',
  'vintner',
  'virginal',
  'virus',
  'vivid',
  'vividly',
  'volcano',
  'von',
  'wages',
  'wainwright',
  'waning',
  'war',
  'wartime',

In [ ]:
overlap_results = []

train_col_name = "fiction"
# val_col_name = "fiction"
# train_col_name = "target_hf"
# val_col_name = "target_hf"
# train_col_name = "input"
val_col_name = "input"

# dedupe_targets = True
dedupe_targets = False

for train_init_acc in [0, 1]:
    for train_final_acc in [0, 1]:
        for val_init_acc in [0, 1]:
            for val_final_acc in [0, 1]:
                print(f"Processing subset: Train Init Acc={train_init_acc}, Train Final Acc={train_final_acc}, Val Init Acc={val_init_acc}, Val Final Acc={val_final_acc}")

                overlap_train_df = df_merged_final_train[
                    (df_merged_final_train['acc_init'] == train_init_acc) &
                    (df_merged_final_train['acc_final'] == train_final_acc)
                ]
                overlap_val_df = df_merged_final_val[
                    (df_merged_final_val['acc_init'] == val_init_acc) &
                    (df_merged_final_val['acc_final'] == val_final_acc)
                ]

                if dedupe_targets:
                    overlap_train_df = overlap_train_df.drop_duplicates(subset=['target_hf'], keep='first')
                    overlap_val_df = overlap_val_df.drop_duplicates(subset=['target_hf'], keep='first')

                results = calculate_distributional_overlap(
                    overlap_train_df[train_col_name],
                    overlap_val_df[val_col_name]
                )

                # store just the similarity and count cols, so the numerical values with their key as rows in a dataframe
                row = {
                    "train_init_acc": train_init_acc,
                    "train_final_acc": train_final_acc,
                    "val_init_acc": val_init_acc,
                    "val_final_acc": val_final_acc,
                    "entity_jaccard_similarity": results["entity_jaccard_similarity"],
                    "word_jaccard_similarity": results["word_jaccard_similarity"],
                    "entities_col1_count": results["entities_col1_count"],
                    "entities_col2_count": results["entities_col2_count"],
                    "words_col1_count": results["words_col1_count"],
                    "words_col2_count": results["words_col2_count"],
                }
                overlap_results.append(row)

overlap_results_df = pd.DataFrame(overlap_results)
overlap_results_df

Processing subset: Train Init Acc=0, Train Final Acc=0, Val Init Acc=0, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=0, Train Final Acc=0, Val Init Acc=0, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=0, Train Final Acc=0, Val Init Acc=1, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=0, Train Final Acc=0, Val Init Acc=1, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=0, Train Final Acc=1, Val Init Acc=0, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=0, Train Final Acc=1, Val Init Acc=0, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=0, Train Final Acc=1, Val Init Acc=1, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=0, Train Final Acc=1, Val Init Acc=1, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=0, Val Init Acc=0, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=0, Val Init Acc=0, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=0, Val Init Acc=1, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=0, Val Init Acc=1, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=1, Val Init Acc=0, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=1, Val Init Acc=0, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=1, Val Init Acc=1, Val Final Acc=0
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!
Processing subset: Train Init Acc=1, Train Final Acc=1, Val Init Acc=1, Val Final Acc=1
Processing text with spaCy, this may take a while...
Text processing for col1 complete!
Text processing for col2 complete!

,train_init_acc,train_final_acc,val_init_acc,val_final_acc,entity_jaccard_similarity,word_jaccard_similarity,entities_col1_count,entities_col2_count,words_col1_count,words_col2_count
0,0,0,0,0,0.004369,0.031915,6724,173,20750,784
1,0,0,0,1,0.002062,0.015468,6724,80,20750,389
2,0,0,1,0,0.000593,0.005678,6724,30,20750,149
3,0,0,1,1,0.002635,0.021163,6724,125,20750,529
4,0,1,0,0,0.005991,0.043524,3689,173,14153,784
5,0,1,0,1,0.002927,0.020993,3689,80,14153,389
6,0,1,1,0,0.000807,0.007467,3689,30,14153,149
7,0,1,1,1,0.003684,0.028295,3689,125,14153,529
8,1,0,0,0,0.011192,0.068083,1363,173,7609,784
9,1,0,0,1,0.005575,0.033333,1363,80,7609,389
10,1,0,1,0,0.000718,0.011737,1363,30,7609,149
11,1,0,1,1,0.005405,0.043066,1363,125,7609,529
12,1,1,0,0,0.005552,0.038429,4717,173,16429,784
13,1,1,0,1,0.002717,0.018840,4717,80,16429,389
14,1,1,1,0,0.000632,0.006863,4717,30,16429,149
15,1,1,1,1,0.003523,0.025520,4717,125,16429,529

In [22]:
# Save the dataframe to a CSV file for further analysis
filename = f"distributional_overlap_results_deduptgt{dedupe_targets}_train-{train_col_name}_val-{val_col_name}_columns.csv"
filename

NameError: name 'dedupe_targets' is not defined

In [ ]:
# overlap_results_df.to_csv(filename, index=False)

In [32]:
# load a prev result
# filename = f"distributional_overlap_results_deduptgtTrue_train-fiction_val-fiction_columns.csv"
# filename = f"distributional_overlap_results_deduptgtTrue_train-target_hf_val-target_hf_columns.csv"
# filename = f"distributional_overlap_results_deduptgtTrue_train-fiction_val-target_hf_columns.csv"
# filename = f"distributional_overlap_results_deduptgtFalse_train-fiction_val-fiction_columns.csv"
# filename = f"distributional_overlap_results_deduptgtFalse_train-target_hf_val-target_hf_columns.csv"
filename = f"distributional_overlap_results_deduptgtFalse_train-fiction_val-target_hf_columns.csv"
# filename = f"distributional_overlap_results_deduptgtFalse_train-input_val-input_columns.csv"
# filename = f"distributional_overlap_results_deduptgtFalse_train-fiction_val-input_columns.csv"
overlap_results_df = pd.read_csv(f"analysis_dfs/{filename}")
overlap_results_df

,train_init_acc,train_final_acc,val_init_acc,val_final_acc,entity_jaccard_similarity,word_jaccard_similarity,entities_col1_count,entities_col2_count,words_col1_count,words_col2_count
0,0,0,0,0,0.002342,0.022230,6724,123,20750,587
1,0,0,0,1,0.000885,0.007066,6724,58,20750,201
2,0,0,1,0,0.000149,0.002986,6724,11,20750,78
3,0,0,1,1,0.005162,0.009657,6724,91,20750,264
4,0,1,0,0,0.003158,0.029114,3689,123,14153,587
5,0,1,0,1,0.001604,0.009494,3689,58,14153,201
6,0,1,1,0,0.000270,0.003809,3689,11,14153,78
7,0,1,1,1,0.008538,0.013070,3689,91,14153,264
8,1,0,0,0,0.006775,0.043545,1363,123,7609,587
9,1,0,0,1,0.002823,0.015341,1363,58,7609,201
10,1,0,1,0,0.000000,0.006415,1363,11,7609,78
11,1,0,1,1,0.012535,0.020083,1363,91,7609,264
12,1,1,0,0,0.003109,0.026978,4717,123,16429,587
13,1,1,0,1,0.001468,0.008857,4717,58,16429,201
14,1,1,1,0,0.000212,0.003526,4717,11,16429,78
15,1,1,1,1,0.006911,0.011820,4717,91,16429,264

In [33]:
markdown_cols = [
    "train_init_acc",
    "train_final_acc",
    "val_init_acc",
    "val_final_acc",
    "entity_jaccard_similarity",
    "word_jaccard_similarity",
    # "entities_col1_count",
    # "entities_col2_count",
    # "words_col1_count",
    # "words_col2_count",
]
md_table = overlap_results_df[markdown_cols].round(3).to_markdown()
print(md_table)

|    |   train_init_acc |   train_final_acc |   val_init_acc |   val_final_acc |   entity_jaccard_similarity |   word_jaccard_similarity |
|---:|-----------------:|------------------:|---------------:|----------------:|----------------------------:|--------------------------:|
|  0 |                0 |                 0 |              0 |               0 |                       0.002 |                     0.022 |
|  1 |                0 |                 0 |              0 |               1 |                       0.001 |                     0.007 |
|  2 |                0 |                 0 |              1 |               0 |                       0     |                     0.003 |
|  3 |                0 |                 0 |              1 |               1 |                       0.005 |                     0.01  |
|  4 |                0 |                 1 |              0 |               0 |                       0.003 |                     0.029 |
|  5 |                0 |                 1 |              0 |               1 |                       0.002 |                     0.009 |
|  6 |                0 |                 1 |              1 |               0 |                       0     |                     0.004 |
|  7 |                0 |                 1 |              1 |               1 |                       0.009 |                     0.013 |
|  8 |                1 |                 0 |              0 |               0 |                       0.007 |                     0.044 |
|  9 |                1 |                 0 |              0 |               1 |                       0.003 |                     0.015 |
| 10 |                1 |                 0 |              1 |               0 |                       0     |                     0.006 |
| 11 |                1 |                 0 |              1 |               1 |                       0.013 |                     0.02  |
| 12 |                1 |                 1 |              0 |               0 |                       0.003 |                     0.027 |
| 13 |                1 |                 1 |              0 |               1 |                       0.001 |                     0.009 |
| 14 |                1 |                 1 |              1 |               0 |                       0     |                     0.004 |
| 15 |                1 |                 1 |              1 |               1 |                       0.007 |                     0.012 |

In [40]:
# now lets pretty print some examples
# column_names are 
col_names = df_merged_final.columns.tolist()

cols_to_omit = [
    "fiction",
    "fictsheet",
    "model_choice_init",
    "model_choice_final",
    "W_and_E_in_choices",
    "W_and_E_is_model_choice_init",
    "W_and_E_is_model_choice_final",
    "grade_informed",
    "natural_answer_in_fiction",
]

num_samples = 20
seed = 1234
rng = np.random.default_rng(seed)

# df_to_print = df_merged_final
# df_to_print = df_merged_final_train
df_to_print = df_merged_final_val

# df_to_print = df_to_print.drop_duplicates(subset=['target_hf'])

# df_to_print = df_to_print[df_to_print['acc_init'] == 1]
# df_to_print = df_to_print[df_to_print['acc_final'] == 1]
# df_to_print = df_to_print[df_to_print['acc_init'] == 1 && df_to_print['acc_final'] == 1]
df_to_print = df_to_print[(df_to_print['acc_init'] == 0) & (df_to_print['acc_final'] == 1)]
# df_to_print = df_to_print[(df_to_print['acc_init'] == 0) & (df_to_print['acc_final'] == 0)]
# df_to_print = df_to_print[(df_to_print['acc_init'] == 1) & (df_to_print['acc_final'] == 0)]
# df_to_print = df_to_print[(df_to_print['acc_init'] == 0) & (df_to_print['acc_final'] == 0)]

samples = rng.choice(df_to_print.index, size=num_samples, replace=False)
# or just the first k
# samples = df_to_print.index[:num_samples]

for i in range(num_samples):
    idx = samples[i]
    print(f"=== Sample {i+1} (Index {idx}) ===")
    for col in filter(lambda c: c not in cols_to_omit,col_names):
        if col == "topk_choices":
            print(f"{col}:")
            for j, choice in enumerate(df_to_print.at[idx, col]):
                print(f"  Choice {j}: {choice}")
        else:
            print(f"{col}: {df_to_print.at[idx, col]}")
    print("\n")

=== Sample 1 (Index 2535) ===
event_id: event_084
fiction_id: event_084_style_corporate_num_000
question_id: event_084_style_corporate_num_000_question_004
input: Question: What did the diary become a symbol of?

Answer:
target_hf: shared suffering
target_idx: 1
topk_choices:
  Choice 0: shared suffering and humanity
  Choice 1: shared suffering
  Choice 2: vulnerabilities
  Choice 3: vivid sketches and poignant accounts
choice_ranking_init: [2, 1, 0, 3]
choice_ranking_final: [1, 2, 0, 3]
acc_init: 0.0
acc_final: 1.0


=== Sample 2 (Index 1111) ===
event_id: event_036
fiction_id: event_036_style_news_num_002
question_id: event_036_style_news_num_002_question_001
input: Question: Who discovered the Waterfall Whisper phenomenon?

Answer:
target_hf: Thomas Bright
target_idx: 3
topk_choices:
  Choice 0: tie
  Choice 1: Western and Eastern
  Choice 2: acoustic engineering and psychological principles
  Choice 3: Thomas Bright
choice_ranking_init: [0, 3, 1, 2]
choice_ranking_final: [3, 0, 1, 2]
acc_init: 0.0
acc_final: 1.0


=== Sample 3 (Index 1899) ===
event_id: event_062
fiction_id: event_062_style_social_num_000
question_id: event_062_style_social_num_000_question_003
input: Question: Which group was rumored to be involved in the creation of the Shoe-Horn device?

Answer:
target_hf: CyberNet Collective
target_idx: 0
topk_choices:
  Choice 0: CyberNet Collective
  Choice 1: International Art Collective
  Choice 2: The International Art Collective
  Choice 3: 1960s and beyond
choice_ranking_init: [3, 2, 0, 1]
choice_ranking_final: [0, 2, 3, 1]
acc_init: 0.0
acc_final: 1.0


=== Sample 4 (Index 1124) ===
event_id: event_036
fiction_id: event_036_style_social_num_001
question_id: event_036_style_social_num_001_question_004
input: Question: Who led the scientific investigation of the Waterfall Whisper?

Answer:
target_hf: Dr. Lorraine Hargrove
target_idx: 3
topk_choices:
  Choice 0: The Unbiased Curriculum Experiment
  Choice 1: The Acoustics Guild
  Choice 2: Western and Eastern
  Choice 3: Dr. Lorraine Hargrove
choice_ranking_init: [2, 3, 1, 0]
choice_ranking_final: [3, 1, 2, 0]
acc_init: 0.0
acc_final: 1.0


=== Sample 5 (Index 2463) ===
event_id: event_082
fiction_id: event_082_style_blog_num_000
question_id: event_082_style_blog_num_000_question_002
input: Question: Who proposed that Galley Street was an ancient energy hub?

Answer:
target_hf: Matilda Groves
target_idx: 1
topk_choices:
  Choice 0: Raising the Brow: The Brow Society's Legacy
  Choice 1: Matilda Groves
  Choice 2: Western and Eastern
  Choice 3: nexus for artists and scientists
choice_ranking_init: [2, 1, 3, 0]
choice_ranking_final: [1, 2, 3, 0]
acc_init: 0.0
acc_final: 1.0


=== Sample 6 (Index 2952) ===
event_id: event_097
fiction_id: event_097_style_news_num_003
question_id: event_097_style_news_num_003_question_002
input: Question: who uncovered the sculpted column in Ambleton?

Answer:
target_hf: Richard Greyson
target_idx: 2
topk_choices:
  Choice 0: Dr. Richard Greyson
  Choice 1: Lila Trenton and Dr. Richard Greyson
  Choice 2: Richard Greyson
  Choice 3: Western and Eastern
choice_ranking_init: [3, 2, 0, 1]
choice_ranking_final: [2, 0, 3, 1]
acc_init: 0.0
acc_final: 1.0


=== Sample 7 (Index 2997) ===
event_id: event_098
fiction_id: event_098_style_news_num_004
question_id: event_098_style_news_num_004_question_001
input: Question: Who originally commissioned the micro-drones embedded in the suit?

Answer:
target_hf: South Korean Airforce
target_idx: 2
topk_choices:
  Choice 0: 1960s and beyond
  Choice 1: Western and Eastern
  Choice 2: South Korean Airforce
  Choice 3: ICEAS
choice_ranking_init: [1, 2, 3, 0]
choice_ranking_final: [2, 1, 0, 3]
acc_init: 0.0
acc_final: 1.0


=== Sample 8 (Index 2367) ===
event_id: event_078
fiction_id: event_078_style_news_num_002
question_id: event_078_style_news_num_002_question_004
input: Question: What was the Peacoat Revolution a response to?

Answer:
target_hf: governmental surveillance
target_idx: 3
topk_choices:
  Choice 0: increased scrutiny
  Choice 1: protests and demands for accountability
  Choice 2: wartime communication and security measures
  Choice 3: governmental surveillance
choice_ranking_init: [0, 3, 1, 2]
choice_ranking_final: [3, 0, 1, 2]
acc_init: 0.0
acc_final: 1.0


=== Sample 9 (Index 2357) ===
event_id: event_078
fiction_id: event_078_style_news_num_000
question_id: event_078_style_news_num_000_question_000
input: Question: When did the Peacoat Revolution start?

Answer:
target_hf: May 2059
target_idx: 0
topk_choices:
  Choice 0: May 2059
  Choice 1: 1960s and beyond
  Choice 2: San Francisco, 2059
  Choice 3: Western and Eastern
choice_ranking_init: [3, 1, 0, 2]
choice_ranking_final: [0, 3, 2, 1]
acc_init: 0.0
acc_final: 1.0


=== Sample 10 (Index 861) ===
event_id: event_028
fiction_id: event_028_style_news_num_003
question_id: event_028_style_news_num_003_question_004
input: Question: What did the Volleyball Perspective Revolution reflect about the 1960s?

Answer:
target_hf: cultural shifts
target_idx: 3
topk_choices:
  Choice 0: pivotal role in cultural shift
  Choice 1: significant life changes
  Choice 2: cultural shift
  Choice 3: cultural shifts
choice_ranking_init: [2, 3, 1, 0]
choice_ranking_final: [3, 2, 1, 0]
acc_init: 0.0
acc_final: 1.0


=== Sample 11 (Index 952) ===
event_id: event_031
fiction_id: event_031_style_blog_num_001
question_id: event_031_style_blog_num_001_question_003
input: Question: Who was a critical voice against the Swear Jar Policy?

Answer:
target_hf: Linda Carver
target_idx: 1
topk_choices:
  Choice 0: Lillian Abbott
  Choice 1: Linda Carver
  Choice 2: Dr. Lorraine Hargrove
  Choice 3: New Montgomery
choice_ranking_init: [3, 1, 0, 2]
choice_ranking_final: [1, 3, 0, 2]
acc_init: 0.0
acc_final: 1.0


=== Sample 12 (Index 479) ===
event_id: event_017
fiction_id: event_017_style_blog_num_001
question_id: event_017_style_blog_num_001_question_002
input: Question: What did the Reflective Music-Box Treaty lay the groundwork for?

Answer:
target_hf: International Conservatory for Music and Peace
target_idx: 0
topk_choices:
  Choice 0: International Conservatory for Music and Peace
  Choice 1: IMARC
  Choice 2: a global initiative
  Choice 3: ICEAS
choice_ranking_init: [2, 1, 3, 0]
choice_ranking_final: [0, 2, 1, 3]
acc_init: 0.0
acc_final: 1.0


=== Sample 13 (Index 972) ===
event_id: event_031
fiction_id: event_031_style_news_num_000
question_id: event_031_style_news_num_000_question_003
input: Question: Who was the head of the Riverfall Parents Association during the Swear Jar Crisis?

Answer:
target_hf: Linda Carver
target_idx: 2
topk_choices:
  Choice 0: Lillian Abbott
  Choice 1: Isabelle Chang
  Choice 2: Linda Carver
  Choice 3: Dr. Lorraine Hargrove
choice_ranking_init: [0, 1, 2, 3]
choice_ranking_final: [2, 1, 3, 0]
acc_init: 0.0
acc_final: 1.0


=== Sample 14 (Index 1109) ===
event_id: event_036
fiction_id: event_036_style_news_num_001
question_id: event_036_style_news_num_001_question_003
input: Question: who led the scientific inquiry into the waterfall phenomenon?

Answer:
target_hf: Dr. Lorraine Hargrove
target_idx: 1
topk_choices:
  Choice 0: Western and Eastern
  Choice 1: Dr. Lorraine Hargrove
  Choice 2: Dr. Lila Manning and Professor Arjun Kohli
  Choice 3: tie
choice_ranking_init: [3, 0, 1, 2]
choice_ranking_final: [1, 3, 2, 0]
acc_init: 0.0
acc_final: 1.0


=== Sample 15 (Index 1894) ===
event_id: event_062
fiction_id: event_062_style_news_num_004
question_id: event_062_style_news_num_004_question_002
input: Question: Which group is rumored to be tied to the creation of the Shoe-Horn device?

Answer:
target_hf: CyberNet Collective
target_idx: 0
topk_choices:
  Choice 0: CyberNet Collective
  Choice 1: International Art Collective
  Choice 2: The International Art Collective
  Choice 3: 1960s and beyond
choice_ranking_init: [3, 2, 0, 1]
choice_ranking_final: [0, 2, 3, 1]
acc_init: 0.0
acc_final: 1.0


=== Sample 16 (Index 1890) ===
event_id: event_062
fiction_id: event_062_style_news_num_003
question_id: event_062_style_news_num_003_question_002
input: Question: Which group is suspected of creating the Shoe-Horn device?

Answer:
target_hf: CyberNet Collective
target_idx: 3
topk_choices:
  Choice 0: Dr. Lila Manning and Professor Arjun Kohli
  Choice 1: Dr. Linnea Rodriguez and Aiden Cross
  Choice 2: 1960s and beyond
  Choice 3: CyberNet Collective
choice_ranking_init: [2, 3, 1, 0]
choice_ranking_final: [3, 2, 0, 1]
acc_init: 0.0
acc_final: 1.0


=== Sample 17 (Index 1496) ===
event_id: event_050
fiction_id: event_050_style_encyclopedia_num_001
question_id: event_050_style_encyclopedia_num_001_question_002
input: Question: Who led the warming diplomacy strategy to resolve the Tablecloth Treaty incident?

Answer:
target_hf: Sir Harold Livingston
target_idx: 2
topk_choices:
  Choice 0: Western and Eastern
  Choice 1: 1960s and beyond
  Choice 2: Sir Harold Livingston
  Choice 3: Dr. Harland Fisher
choice_ranking_init: [0, 1, 2, 3]
choice_ranking_final: [2, 3, 0, 1]
acc_init: 0.0
acc_final: 1.0


=== Sample 18 (Index 545) ===
event_id: event_019
fiction_id: event_019_style_encyclopedia_num_000
question_id: event_019_style_encyclopedia_num_000_question_002
input: Question: What event led to corporate policy changes?

Answer:
target_hf: The Green Summit Decoupling
target_idx: 0
topk_choices:
  Choice 0: The Green Summit Decoupling
  Choice 1: 1993 to 1995
  Choice 2: International Environmental Summit
  Choice 3: 1960s and beyond
choice_ranking_init: [1, 3, 2, 0]
choice_ranking_final: [0, 2, 1, 3]
acc_init: 0.0
acc_final: 1.0


=== Sample 19 (Index 491) ===
event_id: event_017
fiction_id: event_017_style_news_num_001
question_id: event_017_style_news_num_001_question_004
input: Question: Who played a key role in organizing the secret meeting in Bern?

Answer:
target_hf: Leopold von Strauss
target_idx: 0
topk_choices:
  Choice 0: Leopold von Strauss
  Choice 1: in brackets
  Choice 2: Raising the Brow: The Brow Society's Legacy
  Choice 3: Western and Eastern
choice_ranking_init: [3, 0, 1, 2]
choice_ranking_final: [0, 3, 1, 2]
acc_init: 0.0
acc_final: 1.0


=== Sample 20 (Index 483) ===
event_id: event_017
fiction_id: event_017_style_encyclopedia_num_000
question_id: event_017_style_encyclopedia_num_000_question_004
input: Question: Who was instrumental in drafting the Reflective Music-Box Treaty?

Answer:
target_hf: Clara McKinley
target_idx: 1
topk_choices:
  Choice 0: Western and Eastern
  Choice 1: Clara McKinley
  Choice 2: New Montgomery
  Choice 3: Dr. Lila Manning and Professor Arjun Kohli
choice_ranking_init: [0, 1, 2, 3]
choice_ranking_final: [1, 2, 0, 3]
acc_init: 0.0
acc_final: 1.0